# Generated by Django 4.2.16 on 2024-11-22 23:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="icons/profile-placeholder.wepb",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
