# Generated by Django 4.2.16 on 2024-11-26 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="default-profile", max_length=255, verbose_name="image"
            ),
        ),
    ]
