# Generated by Django 4.2.16 on 2024-11-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contact_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
    ]
