# Generated by Django 4.2.16 on 2024-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_remove_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default="gunnar", max_length=200),
            preserve_default=False,
        ),
    ]
