# Generated by Django 4.2.16 on 2024-11-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_alt",
            field=models.CharField(max_length=100),
        ),
    ]
