# Generated by Django 4.2.16 on 2024-11-19 09:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/logo/logo6.webp', force_format='WEPB', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='description of the image', max_length=100),
        ),
    ]
