# Generated by Django 4.2.16 on 2024-11-19 15:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_excerpt_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/logo/logo6.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='blog/images'),
        ),
    ]
