# Generated by Django 4.2.16 on 2024-11-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='status',
        ),
    ]
